[package]
name = "rpcl"
version = "0.1.0"
authors = ["tdgne"]
edition = "2018"

[dependencies]
walkdir = "2"
clap = "2.33"
crossterm = "0.11.1"
number_prefix = "0.3.0"
strfmt = "0.1.6"
ignore = "0.4.10"
